# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniMamba',
                'doc_host': 'https://ParticularlyPythonicBS.github.io',
                'git_url': 'https://github.com/ParticularlyPythonicBS/miniMamba',
                'lib_path': 'miniMamba'},
  'syms': { 'miniMamba.core': {'miniMamba.core.foo': ('model.html#foo', 'miniMamba/core.py')},
            'miniMamba.modelArgs': { 'miniMamba.modelArgs.ModelArgs': ('modelargs.html#modelargs', 'miniMamba/modelArgs.py'),
                                     'miniMamba.modelArgs.ModelArgs.__post_init__': ( 'modelargs.html#modelargs.__post_init__',
                                                                                      'miniMamba/modelArgs.py')}}}
