# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniMamba',
                'doc_host': 'https://ParticularlyPythonicBS.github.io',
                'git_url': 'https://github.com/ParticularlyPythonicBS/miniMamba',
                'lib_path': 'miniMamba'},
  'syms': {'miniMamba.core': {'miniMamba.core.foo': ('core.html#foo', 'miniMamba/core.py')}}}
