# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/modelArgs.ipynb.

# %% ../nbs/modelArgs.ipynb 3
from __future__ import annotations
from dataclasses import dataclass
import math

# %% auto 0
__all__ = ['ModelArgs']

# %% ../nbs/modelArgs.ipynb 4
@dataclass
class ModelArgs:
    d_model: int
    n_layer: int
    vocab_size: int
    d_state: int = 16
    expand: int = 2
    dt_rank: Union[int, str] = 'auto'
    d_conv: int = 4 
    pad_vocab_size_multiple: int = 8
    conv_bias: bool = True
    bias: bool = False
    
    def __post_init__(self):
        self.d_inner = int(self.expand * self.d_model)
        
        if self.dt_rank == 'auto':
            self.dt_rank = math.ceil(self.d_model / 16)
            
        if self.vocab_size % self.pad_vocab_size_multiple != 0:
            self.vocab_size += (self.pad_vocab_size_multiple
                                - self.vocab_size % self.pad_vocab_size_multiple)
